name: release
on:
  push:
    branches: [ master, main ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: git checkout HEAD^
      - uses: fabasoad/data-format-converter-action@main
        id: xml2json
        with:
          input: 'Config/module.xml'
          from: 'xml'
          to: 'json'
      - name: Print result
        run: echo "${{ steps.xml2json.outputs.output }}"          
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{fromJson(steps.xml2json.outputs.output).version}}
  
