name: release
on:
  push:
    branches: [ master, main ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: git checkout HEAD^
      - name: Get Version
        id: get_version
        uses: QwerMike/xpath-action@v1
        with:
          filename: 'Config/module.xml'
          expression: '//version/text()'
      - name: Print result
        run: echo "${{ steps.get_version.outputs }}"          
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{fromJson(steps.get_version.outputs.output).version}}
  
